# Generated by Django 4.2.28 on 2026-02-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiry', models.DateField()),
                ('license_category', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('bike', 'Bike')], max_length=10)),
                ('safety_score', models.FloatField(default=100.0)),
                ('status', models.CharField(choices=[('on_duty', 'On Duty'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], default='off_duty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
