# Generated by Django 4.2.28 on 2026-02-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaintenanceLog',
        ),
    ]
